on:
  push:
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10
name: Create prerelease w/ binaries and static assets
jobs:
  build-push-go:
    name: go
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to GHCR
        id: login-ghcr
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build
        run: |
          DOCKER_BUILDKIT=1 docker build -f ./go/Dockerfile \
            -t ghcr.io/hatchet-dev/managed-worker-quickstarts/go:latest \
            --platform linux/amd64 \
            .
      - name: Push to GHCR
        run: |
          docker push ghcr.io/hatchet-dev/managed-worker-quickstarts/go:latest
  build-push-python:
    name: python
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to GHCR
        id: login-ghcr
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build
        run: |
          DOCKER_BUILDKIT=1 docker build -f ./python/Dockerfile \
            -t ghcr.io/hatchet-dev/managed-worker-quickstarts/python:latest \
            --platform linux/amd64 \
            .
      - name: Push to GHCR
        run: |
          docker push ghcr.io/hatchet-dev/managed-worker-quickstarts/python:latest
  build-push-typescript:
    name: typescript
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to GHCR
        id: login-ghcr
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build
        run: |
          DOCKER_BUILDKIT=1 docker build -f ./typescript/Dockerfile \
            -t ghcr.io/hatchet-dev/managed-worker-quickstarts/typescript:latest \
            --platform linux/amd64 \
            .
      - name: Push to GHCR
        run: |
          docker push ghcr.io/hatchet-dev/managed-worker-quickstarts/typescript:latest
